#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug  5 10:52:36 2020

@author: donghui
"""


import os
import math
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import matplotlib.lines as lines
import seaborn as sns
import warnings; warnings.filterwarnings(action='once')

from scipy.spatial import ConvexHull

df = pd.read_csv("/home/donghui/test/economics.csv", parse_dates=['date']).head(100)

x= np.arange(df.shape[0])

y_returns =(df.psavert.diff().fillna(0)/df.psavert.shift(1)).fillna(0)*100

plt.figure(figsize=(16,10),dpi=80)

plt.fill_between(x[1:],y_returns[1:],0,where=y_returns[1:]>=0,facecolor='green',
                 interpolate=True,alpha=0.7)
plt.fill_between(x[1:],y_returns[1:],0,where=y_returns[1:]<=0,facecolor='red',
                 interpolate=True,alpha=0.7)

plt.annotate('Peak 1975',xy=(94.0,21.0),xytext=(88.0,28),
             bbox=dict(boxstyle='square',fc='firebrick'),
             arrowprops=dict(facecolor='steelblue',shrink=0.05), fontsize=15,color='white')

xtickvals= [str(m)[:3].upper()+"-"+str(y) for y,m in zip(df.date.dt.year,df.date.dt.month_name())]

plt.gca().set_xticks(x[::6])
plt.gca().set_xticklabels(xtickvals[::6],rotation=90,fontdict={'horizontalalignment':'center','verticalalignment':'center_baseline'})

plt.ylim(-35,35)
plt.xlim(1,100)
plt.title("Month Economics Return %",fontsize=22)
plt.ylabel("Monthly Return %")
plt.grid(alpha=0.5)
plt.show()
