#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Aug  2 21:47:54 2020

@author: donghui
"""

import os
import math
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import matplotlib.lines as lines
import seaborn as sns
import warnings; warnings.filterwarnings(action='once')

from scipy.spatial import ConvexHull

large=22; med=16; small=12
params={'axes.labelsize':med,
        'axes.titlesize':med,
        'xtick.labelsize':med,
        'ytick.labelsize':med,
        'legend.fontsize':med,
        'figure.figsize':(16,10),
        'figure.titlesize':large}
plt.rcParams.update(params)
plt.style.use('seaborn-whitegrid')
sns.set_style('white')

print(mpl.__version__)
print(sns.__version__)

midwest=pd.read_csv("/home/donghui/test/midwest_filter.csv")
#nsex=mydata.sex.dropna()
    
categories=np.unique(midwest['category'])
colors=[plt.cm.tab10(i/float(len(categories)-1)) for i in range(len(categories))]

plt.figure(figsize=(16,10),dpi=80,facecolor='w',edgecolor='k')

for i,category in enumerate(categories):
     plt.scatter('area','poptotal',data=midwest.loc[midwest.category==category,:],
     s=20,c=colors[i],label=str(category))
  
plt.gca().set(xlim=(0,0.1),ylim=(0,90000),
             xlabel='Area',ylabel='Population')

plt.xticks(fontsize=12);
plt.yticks(fontsize=12)
plt.title("Midwest Area vs Population",fontsize=22)
plt.legend(fontsize=12)
plt.show()


import warnings;warnings.simplefilter('ignore')
sns.set_style("white")

for i, category in enumerate(categories):
    plt.scatter('area','poptotal',data=midwest.loc[midwest.category==category,:],
                s='dot_size',c=colors[i],label=str(category),edgecolors='black',linewidths=.5)

def encircle(x,y,ax=None,**kw):
    if not ax:ax=plt.gca()
    p=np.c_[x,y]
    hull=ConvexHull(p)
    poly=plt.Polygon(p[hull.vertices,:],**kw)
    ax.add_patch(poly)
    
midwest_encircle_data=midwest.loc[midwest.state=='IN',:]

encircle(midwest_encircle_data.area,midwest_encircle_data.poptotal,ec="k",fc="gold",alpha=0.1)

encircle(midwest_encircle_data.area,midwest_encircle_data.poptotal,ec="firebrick",fc="none",linewidth=1.5)

plt.gca().set(xlim=(0.0,0.1),ylim=(0,90000),xlabel='Area',ylabel='Population')

plt.xticks(fontsize=12)

plt.yticks(fontsize=12)
plt.title("bubble plot",fontsize=22)
plt.legend(fontsize=12)
plt.show()
